//****************************************************************************
// SamUsbHost.h
//
// Created 9/9/2020 12:34:32 PM by Tim
//
//****************************************************************************

#pragma once

enum HostPipeType
{
	USB_HOST_PCFG_PTYPE_DISABLE_Val,
	USB_HOST_PCFG_PTYPE_CONTROL_Val,
	USB_HOST_PCFG_PTYPE_ISOCHRONOUS_Val,
	USB_HOST_PCFG_PTYPE_BULK_Val,
	USB_HOST_PCFG_PTYPE_INTERRUPT_Val,
	USB_HOST_PCFG_PTYPE_EXTENDED_Val,
};

enum HostPipeToken
{
	USB_HOST_PCFG_PTOKEN_SETUP_Val,
	USB_HOST_PCFG_PTOKEN_IN_Val,
	USB_HOST_PCFG_PTOKEN_OUT_Val
};

#define USB_HOST_PCFG_PTYPE_DISABLE		USB_HOST_PCFG_PTYPE(USB_HOST_PCFG_PTYPE_DISABLE_Val)
#define USB_HOST_PCFG_PTYPE_CONTROL		USB_HOST_PCFG_PTYPE(USB_HOST_PCFG_PTYPE_CONTROL_Val)
#define USB_HOST_PCFG_PTYPE_ISOCHRONOUS	USB_HOST_PCFG_PTYPE(USB_HOST_PCFG_PTYPE_ISOCHRONOUS_Val)
#define USB_HOST_PCFG_PTYPE_BULK		USB_HOST_PCFG_PTYPE(USB_HOST_PCFG_PTYPE_BULK_Val)
#define USB_HOST_PCFG_PTYPE_INTERRUPT	USB_HOST_PCFG_PTYPE(USB_HOST_PCFG_PTYPE_INTERRUPT_Val)
#define USB_HOST_PCFG_PTYPE_EXTENDED	USB_HOST_PCFG_PTYPE(USB_HOST_PCFG_PTYPE_EXTENDED_Val)

#define USB_HOST_PCFG_PTOKEN_SETUP		USB_HOST_PCFG_PTOKEN(USB_HOST_PCFG_PTOKEN_SETUP_Val)
#define USB_HOST_PCFG_PTOKEN_IN			USB_HOST_PCFG_PTOKEN(USB_HOST_PCFG_PTOKEN_IN_Val)
#define USB_HOST_PCFG_PTOKEN_OUT		USB_HOST_PCFG_PTOKEN(USB_HOST_PCFG_PTOKEN_OUT_Val)
